---
title: "John Hopkins COVID-2019"
author: "David J Jackson"
date: "3/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```
```{r,echo=FALSE}
rm(list=ls())
us_reported <- c("2020-03-27")
us_cases <- c(92929)
us_deaths <- c(1380)
us_recovered <- c(812)
#
world_reported <- c("2020-03-27")
world_cases <- c(566269)
world_deaths <- c(25423)
world_recovered <- c(127768)
#
world_less_cases <- world_cases -us_cases
world_less_deaths <- world_deaths -us_deaths
world_less_recovered <- world_recovered -us_recovered
```
```{r}
df <- data.frame("Reported"  = us_reported, 
                  "us_cases" =us_cases,
                  "us_deaths" = us_deaths,
                 "us_recovered" = us_recovered,
                  "world_cases" = world_cases ,
                 "world_deaths" =  world_deaths,
                  "world_recovered" = world_recovered,
                 "world_less_cases" = world_less_cases,
                 "world_less_deaths" = world_less_deaths,
                 "world_less_recovered" = world_less_recovered
                    )
df$Reported <- as.Date(df$Reported)
```
```{r}
df.us <- data.frame("Reported"  = us_reported, 
                  "Source" = "USA",
                  "Cases" =us_cases,
                  "Deaths" = us_deaths,
                 "Recovered" = us_recovered
                 )
df.us$Reported <- as.Date(df.us$Reported)
```
```{r}
df.world <- data.frame("Reported"  = world_reported,
                  "Source" = "World",
                  "Cases" = world_cases ,
                 "Deaths" =  world_deaths,
                  "Recovered" = world_recovered
                                 )
df.world$Reported <- as.Date(df.world$Reported)
```
```{r}
df.source <- df.source$Reported <- as.Date(df$Reported)

df.source$DeathRate <- df.source$Deaths/df.source$Cases * 100
df.source$RecoveryRate <- df.source$Recovered/df.source$Cases *100

```
```{r}
df.combined <- rbind(df.us,c(Reported,Source,Cases,Deaths,Recovered),
                    df.world,c(Reported,Source,Cases,Deaths,Recovered))
```

## nCOVID-2019 Summary Report for Mar. 27,2020
* Data Source: John Hopkins Coronavirus Resource Center
* URl: https://coronavirus.jhu.edu/map.html


#### US Death Rate: 
```{r}
df$us_deaths/df$us_cases *100
```
#### US Recovery Rate:
```{r}
df$us_recovered/df$us_cases * 100
```
#### World Death Rate(including USA)
```{r}
df$world_deaths/df$world_cases * 100
```
#### World Recovery Rate (including USA)
```{r}
df$world_recovered/df$world_cases * 100
```
#### The world (less USA) Death Rate
```{r}
df$world_less_deaths/df$world_less_cases *100
```
#### The World (less USA) Rate of Recovery
```{r}
df$world_less_recovered/df$world_less_cases *100
```